# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PrepareClientPayload.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PrepareClientPayload(object):
    def setupUi(self, PrepareClientPayload):
        PrepareClientPayload.setObjectName("PrepareClientPayload")
        PrepareClientPayload.resize(400, 300)
        self.widget = QtWidgets.QWidget(PrepareClientPayload)
        self.widget.setGeometry(QtCore.QRect(130, 30, 141, 138))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(PrepareClientPayload)
        QtCore.QMetaObject.connectSlotsByName(PrepareClientPayload)

    def retranslateUi(self, PrepareClientPayload):
        _translate = QtCore.QCoreApplication.translate
        PrepareClientPayload.setWindowTitle(_translate("PrepareClientPayload", "Prepare Client Payload"))
        self.label.setText(_translate("PrepareClientPayload", "Server IP"))
        self.label_2.setText(_translate("PrepareClientPayload", "Server Port"))
        self.pushButton.setText(_translate("PrepareClientPayload", "Generate Payload"))