# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetEmailInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SetEmaiInfo(object):
    def setupUi(self, SetEmaiInfo):
        SetEmaiInfo.setObjectName("SetEmaiInfo")
        SetEmaiInfo.resize(400, 301)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Angrycat.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SetEmaiInfo.setWindowIcon(icon)
        self.splitter = QtWidgets.QSplitter(SetEmaiInfo)
        self.splitter.setGeometry(QtCore.QRect(140, 20, 137, 241))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.SenderEmail = QtWidgets.QLineEdit(self.splitter)
        self.SenderEmail.setObjectName("SenderEmail")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.AppPassword = QtWidgets.QLineEdit(self.splitter)
        self.AppPassword.setObjectName("AppPassword")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setObjectName("label_3")
        self.RecipientEmail = QtWidgets.QLineEdit(self.splitter)
        self.RecipientEmail.setObjectName("RecipientEmail")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(SetEmaiInfo)
        QtCore.QMetaObject.connectSlotsByName(SetEmaiInfo)

    def retranslateUi(self, SetEmaiInfo):
        _translate = QtCore.QCoreApplication.translate
        SetEmaiInfo.setWindowTitle(_translate("SetEmaiInfo", "Set Email Info"))
        self.label.setText(_translate("SetEmaiInfo", "Sender Email"))
        self.label_2.setText(_translate("SetEmaiInfo", "App Passowrd"))
        self.label_3.setText(_translate("SetEmaiInfo", "Recipient Email"))
        self.pushButton.setText(_translate("SetEmaiInfo", "Save"))
